HOST = 'localhost'
CLIENT_PORT = 1800
GENRE_COMPUTATION_PORT = 1801
CRAWLER_RESPONSES_PORT = 1802

# API Paths
# RESOURCE_BASE_PATH = '/api/licenta'
RESOURCE_BASE_PATH = ''

# Songs
SONGS_PATH = f'{RESOURCE_BASE_PATH}/songs'
