USE licenta;
DROP TABLE song_url;
DROP TABLE bloom_filter;
DROP TABLE resource_url;
DROP TABLE crawler_state;
DROP TABLE bill;
DROP TABLE user_to_service;
DROP TABLE service;
DROP TABLE song_info;
DROP TABLE song;
DROP TABLE song_format;
DROP TABLE song_genre;
DROP TABLE user;
DROP TABLE user_type;